#This block is the configuration of the gateway.
spring:
  application:
    name: gateway-service
  cloud:
#    here if we put only discovery gateway do the mapping in default way. If we wannt to configure it according to our needs we add the routes part.
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/cydeo/dev/user/**
          filters:
            - RewritePath=/cydeo/dev/user/(?<segment>.*),/$\{segment}
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/cydeo/dev/project/**
          filters:
            - RewritePath=/cydeo/dev/project/(?<segment>.*),/$\{segment}
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/cydeo/dev/task/**
          filters:
            - RewritePath=/cydeo/dev/task/(?<segment>.*),/$\{segment}

#This is the main port for gateway that will be used for all the requests
server:
  port: 8762


eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/


management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
  context-path: http://localhost:${server.port}/actuator


info:
  application:
    name: ${spring.application.name}
    description: Ticketing Application
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'
