spring:
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://host.docker.internal:9411
  application:
    name: user-service
  profiles:
    active: default
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://host.docker.internal:5435/ticketing-app
    username: postgres
    password: 4432
    driver-class-name: org.postgresql.Driver
server:
  port: 9393
#eureka, management and info sections all added for the eureka server configuration
eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
  client:
    serviceUrl:
#      Here is important. Here we say the service where to register. That is the address.
      defaultZone: http://discovery-service:8761/eureka/

#here is about actuator which gives us the health of the service.
management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
  context-path: http://localhost:${server.port}/actuator


info:
  application:
    name: ${spring.application.name}
    description: Ticketing Application
#    '@ this sign is taking the information from maven pom. Below we take the variable informations from the parent pom
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'